//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoQuanCapChungNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoQuanCapChungNhan()
        {
            this.GiayChungNhans = new HashSet<GiayChungNhan>();
        }
    
        public string MaCoQuanCap { get; set; }
        public string TenCoQuanCap { get; set; }
        public string DiaChiCoQuanCap { get; set; }
        public string SdtCoQuanCap { get; set; }
        public string MaLCS { get; set; }
    
        public virtual LoaiCoSo LoaiCoSo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiayChungNhan> GiayChungNhans { get; set; }
    }
}
