//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSoChanNuoi
    {
        public string MaCoSoCN { get; set; }
        public string TenCSCN { get; set; }
        public string MaVung { get; set; }
        public string MaTCCN { get; set; }
        public string DiaChiCSCN { get; set; }
        public string MaDieuKien { get; set; }
        public string MaDV { get; set; }
        public string MaDichBenh { get; set; }
        public string MaLCS { get; set; }
    
        public virtual DieuKienChanNuoi DieuKienChanNuoi { get; set; }
        public virtual DichBenh DichBenh { get; set; }
        public virtual LoaiCoSo LoaiCoSo { get; set; }
        public virtual ToChucCaNhanChanNuoi ToChucCaNhanChanNuoi { get; set; }
        public virtual Vung Vung { get; set; }
        public virtual DongVatChanNuoi DongVatChanNuoi { get; set; }
    }
}
