//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSoSanXuatSPXLCT
    {
        public int ID_CoSoSanXuatSPXLCT { get; set; }
        public string TenCSSXSPXLCT { get; set; }
        public string DiachiCSSXSPXLCT { get; set; }
        public string SDT_CSSXSPXLCT { get; set; }
    }
}
