//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichBenh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichBenh()
        {
            this.QuanLyKhuTamGius = new HashSet<QuanLyKhuTamGiu>();
        }
    
        public string MaDichBenh { get; set; }
        public string TenDichBenh { get; set; }
        public Nullable<int> MucDoNguyHiem { get; set; }
        public string CachXuLy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyKhuTamGiu> QuanLyKhuTamGius { get; set; }
    }
}
