//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyVungEntities : DbContext
    {
        public QuanLyVungEntities()
            : base("name=QuanLyVungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoQuanCapChungNhan> CoQuanCapChungNhans { get; set; }
        public virtual DbSet<CoSoChanNuoi> CoSoChanNuois { get; set; }
        public virtual DbSet<CoSoKhaoNghiemSPXLCT> CoSoKhaoNghiemSPXLCTs { get; set; }
        public virtual DbSet<CoSoSanXuatSPXLCT> CoSoSanXuatSPXLCTs { get; set; }
        public virtual DbSet<DaiLyThuoc> DaiLyThuocs { get; set; }
        public virtual DbSet<DichBenh> DichBenhs { get; set; }
        public virtual DbSet<DieuKienChanNuoi> DieuKienChanNuois { get; set; }
        public virtual DbSet<DongVatChanNuoi> DongVatChanNuois { get; set; }
        public virtual DbSet<GiayChungNhan> GiayChungNhans { get; set; }
        public virtual DbSet<KhuTamGiu> KhuTamGius { get; set; }
        public virtual DbSet<QuanLyDaiLyThuoc> QuanLyDaiLyThuocs { get; set; }
        public virtual DbSet<QuanLyKhuTamGiu> QuanLyKhuTamGius { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<SP_XL_chat_thai> SP_XL_chat_thai { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongKeChanNuoiNhoLe> ThongKeChanNuoiNhoLes { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
        public virtual DbSet<ToChucCaNhanChanNuoi> ToChucCaNhanChanNuois { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vung> Vungs { get; set; }
    }
}
