//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_dung
    {
        public string IdUser { get; set; }
        public string UserName { get; set; }
        public string Passwords { get; set; }
        public string DisplayName { get; set; }
        public string IdRole { get; set; }
        public string ProvinceId { get; set; }
        public string DistrictId { get; set; }
        public string WardId { get; set; }
    
        public virtual Chuc_vu Chuc_vu { get; set; }
        public virtual Huyen Huyen { get; set; }
        public virtual Tinh Tinh { get; set; }
        public virtual Xa Xa { get; set; }
    }
}
