//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyTamGiuTieuHuy
    {
        public string MaQuanLy { get; set; }
        public string MaKhu { get; set; }
        public string MaDichBenh { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DichBenh DichBenh { get; set; }
        public virtual KhuTamGiu KhuTamGiu { get; set; }
    }
}
