//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyChiCucThuY
    {
        public string MaCCTY { get; set; }
        public string TenCCTY { get; set; }
        public string MaVung { get; set; }
        public string MaLCS { get; set; }
    
        public virtual LoaiCoSo LoaiCoSo { get; set; }
        public virtual Vung Vung { get; set; }
    }
}
