//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeChanNuoiNhoLe
    {
        public string MaThongKe { get; set; }
        public string MaTCCN { get; set; }
        public string MaDV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayThongKe { get; set; }
    
        public virtual DongVatChanNuoi DongVatChanNuoi { get; set; }
        public virtual ToChucCaNhanChanNuoi ToChucCaNhanChanNuoi { get; set; }
    }
}
